### ISSUE TITLE
setup tiny plugin that depends on local_teacheraide

### ISSUE THREAD

**Issue by ycfreeman** [teacheraide/moodle-tiny_teacheraide#3]
![Image](https://github.com/user-attachments/assets/1d6b013e-0dcd-4d05-90d5-05089c2d47ae)

setup a separate tiny plugin that depends on the original chatbot local plugin

**Comment by Maiha192** [comment]
I haven't got much time to look into this further due to multiple assignments due for 2 units. Will definitely spend more time to work on it from next week.
